apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: mindlet
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/part-of: mindlet
data:
  PORT: "3000"
  NODE_ENV: development
