apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: mindlet
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/part-of: mindlet
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - name: http
      port: 3000
      targetPort: http
